name: CI
on: [pull_request]
jobs:
  build:
    name: Pre-merge 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: yarn
      - name: Lint
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          eslint_extensions: .js,.ts,.vue
      - name: Build
        run: yarn build