name: CI
on: [pull_request]
jobs:
  build:
    name: Pre-merge 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build