name: CI
on: [pull_request]
jobs:
  eslint:
    name: ESLint Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ESLint Result
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
          eslint_flags: '--ext .js,.ts,.vue'
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
        run: yarn build